In [1]:
!pip install word2number

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [3]:
df=pd.read_csv('hiring.csv')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [4]:
df.experience=df.experience.fillna('zero')

In [5]:
df.experience = df.experience.apply(w2n.word_to_num)
df 

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [6]:
x=df['test_score(out of 10)'].median()
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(x)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [7]:
ndf=df.drop('salary($)', axis='columns')

In [8]:
reg=linear_model.LinearRegression()
reg.fit(ndf,df['salary($)'])

LinearRegression()

In [9]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [10]:
reg.predict([[2,9,6]])

C:\Users\fadib\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [11]:
reg.predict([[12,10,10]])

C:\Users\fadib\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [12]:
import pickle
f=open('mod','wb')
pickle.dump(reg,f)

In [13]:
f=open('mod','rb')
m=pickle.load(f)

In [14]:
m.predict([[2,9,6]])

C:\Users\fadib\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [15]:
!pip install scikit-learn

In [16]:
import joblib

In [17]:
joblib.dump(reg,'mod_joblib')

['mod_joblib']

In [18]:
x=joblib.load("mod_joblib")

In [19]:
x.predict([[2,9,6]])

C:\Users\fadib\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])