In [7]:
from sklearn.svm import SVC
from sklearn.datasets import load_iris
iris=load_iris()

In [23]:
import numpy as np
import pandas as pd
df=pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [3]:
df['flower']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [4]:
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [12]:
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [9]:
model = SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test, y_test)

0.8888888888888888

In [10]:
#Manually try suppling models with different parameters to cross_val_score function with 5 fold cross validation

In [14]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [16]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [18]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [19]:
#We can use for loop as an alternative

In [24]:
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel=kval,C=cval,gamma='auto'),iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

# Use GridSearchCV

In [37]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(SVC(gamma='auto'),{'C':[1,10,40],'kernel':['rbf','linear']},
                 cv=10, 
                 return_train_score=False)
clf.fit(iris.data, iris.target)   #we need not split, it will be done automatically
clf.cv_results_

{'mean_fit_time': array([0.00101709, 0.00051286, 0.        , 0.00081248, 0.        ,
        0.00156324]),
 'std_fit_time': array([0.00170392, 0.00153859, 0.        , 0.00243745, 0.        ,
        0.00468972]),
 'mean_score_time': array([0.00144281, 0.00032787, 0.00051279, 0.        , 0.00157406,
        0.00121305]),
 'std_score_time': array([0.00276961, 0.00098362, 0.00153837, 0.        , 0.00472219,
        0.00363915]),
 'param_C': masked_array(data=[1, 1, 10, 10, 40, 40],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 40, 'kernel': 'rbf'},
  {'C': 40, 'kernel': 'linear'}],


### make cv_results_ a df for better understanding

In [38]:
pd.DataFrame(clf.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001017      0.001704         0.001443        0.002770       1   
1       0.000513      0.001539         0.000328        0.000984       1   
2       0.000000      0.000000         0.000513        0.001538      10   
3       0.000812      0.002437         0.000000        0.000000      10   
4       0.000000      0.000000         0.001574        0.004722      40   
5       0.001563      0.004690         0.001213        0.003639      40   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}                1.0   
1       linear   {'C': 1, 'kernel': 'linear'}                1.0   
2          rbf     {'C': 10, 'kernel': 'rbf'}                1.0   
3       linear  {'C': 10, 'kernel': 'linear'}                1.0   
4          rbf     {'C': 40, 'kernel': 'rbf'}                1.0   
5       linear  {'C': 40, 'kernel': 'linear'}                1.0   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.933333                1.0           1.000000           1.000000   
1           0.933333                1.0           1.000000           0.866667   
2           0.933333                1.0           1.000000           0.866667   
3           1.000000                1.0           1.000000           0.866667   
4           1.000000                1.0           0.933333           0.866667   
5           1.000000                1.0           1.000000           0.933333   

   split5_test_score  split6_test_score  split7_test_score  split8_test_score  \
0           0.933333           0.933333                1.0                1.0   
1           1.000000           0.933333                1.0                1.0   
2           1.000000           0.933333                1.0                1.0   
3           1.000000           0.933333                1.0                1.0   
4           0.933333           0.866667                1.0                1.0   
5           1.000000           0.866667                1.0                1.0   

   split9_test_score  mean_test_score  std_test_score  rank_test_score  
0                1.0         0.980000        0.030551                1  
1                1.0         0.973333        0.044222                4  
2                1.0         0.973333        0.044222                4  
3                1.0         0.980000        0.042687                1  
4                1.0         0.960000        0.053333                6  
5                1.0         0.980000        0.042687                1

In [39]:
clf.best_score_

0.9800000000000001

In [40]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

#### Use RandomizedSearchCV to reduce number of iterations and with random combination of parameters. This is useful when you have too many parameters to try and your training time is longer. It helps reduce the cost of computation

In [42]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1      20       linear         0.966667

In [43]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [44]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}